apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
  namespace: {{ .Values.customConfig.namespace }}
type: kubernetes.io/dockerconfigjson
data:
   .dockerconfigjson: {{ template "imagePullSecret" . }}
